sudo: required
dist: trusty
language: node_js
node_js:
  - '10.16.0'

branches:
  only:
    - master

before_script:
  - ls
  - npm install -g @angular/cli

script:
  - npm install
  - cd node_modules
  - ls
  - cd ..
  - ng build --prod

after_success:
  - DOCKER_TAG='latest'
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    ls
    docker build -t accoon.pitstop.ui:$DOCKER_TAG -f ./.docker/nginx.dockerfile .
    docker tag accoon.pitstop.ui:$DOCKER_TAG $DOCKER_USERNAME/accoon.pitstop.ui:$DOCKER_TAG
    docker push $DOCKER_USERNAME/accoon.pitstop.ui:$DOCKER_TAG

notifications:
  email:
    on_success: never
    on_failure: always