sudo: required
dist: trusty
language: node_js
node_js:
  - '10.16.0'

branches:
  only:
    - master
    
before_script:
  - ls
  - npm install

script:
  - ./scripts/ng-build.sh

after_success:
  - ./scripts/docker-publish.sh

notifications:
  email:
    on_success: never
    on_failure: always