sudo: required
dist: trusty
language: node_js
node_js:
  - '10.16.0'

branches:
  only:
    - master

before_script:
  - ls
  - npm install -g @angular/cli
  - chmod -R a+x scripts

script:
  - ./scripts/ng-build.sh

after_success:
  - ./scripts/docker-publish.sh

notifications:
  email:
    on_success: never
    on_failure: always